### ISSUE TITLE
Release with updated dependencies

### ISSUE THREAD

**Issue by vhiairrassary** [kamilkisiela/graphql-config#1070]
Could you release a new version as cosmiconfig-typescript-loader [has been updated](https://github.com/kamilkisiela/graphql-config/pull/1069) please, so we can create a PR in https://github.com/dotansimha/graphql-code-generator to use it?

**Comment by vhiairrassary** [comment]
Can I help on this? It [prevents us](https://github.com/kamilkisiela/graphql-config/issues/1039#issuecomment-1166524159) to use the latest versions of typescripts & Jest.

**Comment by B2o5T** [comment]
released in [v4.3.2](https://github.com/kamilkisiela/graphql-config/releases/tag/v4.3.2) sorry for delay (:
