### ISSUE TITLE
Support Prettier with writeSchema()

### ISSUE THREAD

**Issue by brikou** [kamilkisiela/graphql-config#111]
It could be really nice to have prettier support, reading found .prettierrc within the project WDYT?

**Comment by wtrocki** [comment]
You can have post action that supports prettier. Generally, there are couple ways to format things so it is best to do it post write. Prettier has really nice programmatic api.

**Comment by danielrearden** [comment]
Closing this since `graphql-config` no longer exposes a `writeSchema` method. If you need to print the schema, you can use `getSchema` or `getSchemaSync` and then call `printSchema` from the `graphql` module on the returned `GraphQLSchema` object.
