### ISSUE TITLE
esm error throwing `loadTs is not a function`

### ISSUE THREAD

**Issue by mikaelkaron** [kamilkisiela/graphql-config#1113]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `yarn generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

As mentioned in a [downstream issue in `graphql-codegen`](https://github.com/dotansimha/graphql-code-generator/issues/8212) it looks like loading `cosmiconfig-typescript-loader` default export is buggy in esm. The "simple" fix would be to use [`default-import`](https://www.npmjs.com/package/default-import) until this is addressed upstream.

**To Reproduce**

- fetch local copy of https://github.com/dotansimha/graphql-code-generator/tree/master/examples/typescript-esm
- run `npm run codegen`

**Expected behavior**

execution without error

**Environment:**

- OS: Windows
- NodeJS: 18.4
- graphql version: 16.5
- graphql-config version: 4.3.3

**Comment by n1ru4l** [comment]
Closed via https://github.com/kamilkisiela/graphql-config/pull/1103

**Comment by acao** [comment]
@n1ru4l if I'm still getting an issue like this in 4.3.5 is it probably an esbuild bundling issue? Something I need to mark as external?
