### ISSUE TITLE
Found broken `/docs/user/docs/user/usage` link. Please fix!

### ISSUE THREAD

**Issue by persianturtle** [kamilkisiela/graphql-config#1121]
From the VSCode extension's homepage:

![Screen Shot 2022-08-22 at 10 06 26 PM](https://user-images.githubusercontent.com/3474647/186052819-99845e30-822b-4277-9d9a-7be22fab41a9.png)

**Comment by dotansimha** [comment]
Thanks @persianturtle ! We fixed it, now it redirects to https://www.the-guild.dev/graphql/config/docs/user/user-usage
