### ISSUE TITLE
How to use with modular schema without generating an extra file?

### ISSUE THREAD

**Issue by kotojo** [kamilkisiela/graphql-config#114]
My schema definition isn't in a single file for our backend. I have a modular schema https://www.apollographql.com/docs/graphql-tools/generate-schema.html#modularizing and never write it to a file and would like to not have to generate an extra file just to use this tool. Is there a way to pass a glob to the `schemaPath` and have it build the full schema in memory?

**Comment by artisologic** [comment]
I am wondering the exact same thing as I am in a similar situation. Am I missing anything?

**Comment by kotojo** [comment]
Just for future readers of this, I ended up using the [graphql-import](https://github.com/prisma/graphql-import) to accomplish this.

**Comment by eXaminator** [comment]
This issue has been open for a while now. Could someone answer if this is either possible in some way or if it's on the roadmap?

**Comment by HosseinAgha** [comment]
seems like the maintainers are going to assume we are always using Prisma or some tool that generates the `schema.gql` file.  
I think `prisma-graphql-config` would be a better name for this project.

**Comment by ivan-kleshnin** [comment]
Yep. This "forced Prisma" approach is sickening. It's not the first tool that is advertised as universal but really is not.

**Comment by kamilkisiela** [comment]
Hi there, it's [The Guild](http://the-guild.dev/) :) We're working on a new version of GraphQL Config. The goal is to make it platform agnostic, flexible enough to use with any tool and framework, reduce the bundle size and a lot more and what's even more important, bring it back to life and keep maintaining.

New changes #162 are already merged into master and `v3.0.0-alpha.13` is released.

We decided to extract the logic we have in [GraphQL Code Generator](https://graphql-code-generator.com) that's responsible for loading GraphQL Schema and with new GraphQL Config you're able to use your modularized schema (multiple `.graphql`, `.ts` or `.js` files) like this:


```yaml
schema: ./src/modules/**/*.graphql
```
