### ISSUE TITLE
Missing peer dependencies for `cosmiconfig-typescript-loader` and `ts-node`

### ISSUE THREAD

**Issue by mhassan1** [kamilkisiela/graphql-config#1177]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `yarn generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

The `cosmiconfig-typescript-loader` package includes in its `package.json`:
```json
{
  "peerDependencies": {
    "@types/node": "*",
    "cosmiconfig": ">=7",
    "ts-node": ">=10",
    "typescript": ">=3"
  }
}
```
The `ts-node` package includes in its `package.json`:
```json
{
  "peerDependencies": {
    "@types/node": "*",
    "typescript": ">=2.7"
  }
}
```
Neither `@types/node` nor `typescript` are satisfied by `graphql-config`; as a result, I see warnings when I run `yarn`:
```txt
➤ YN0002: │ graphql-config@npm:4.3.6 doesn't provide @types/node, requested by cosmiconfig-typescript-loader
➤ YN0002: │ graphql-config@npm:4.3.6 doesn't provide @types/node, requested by ts-node
➤ YN0002: │ graphql-config@npm:4.3.6 doesn't provide typescript, requested by cosmiconfig-typescript-loader
➤ YN0002: │ graphql-config@npm:4.3.6 doesn't provide typescript, requested by ts-node
```

**To Reproduce**

1. Use Yarn Berry
2. Run `yarn add graphql-config`
3. See warnings, e.g. `graphql-config@npm:4.3.6 doesn't provide @types/node`

**Expected behavior**

No warnings

**Environment:**

- OS: MacOS
- GraphQL Config Version: `4.3.6`
- NodeJS: `16.17.1`

**Comment by B2o5T** [comment]
would be fixed by https://github.com/kamilkisiela/graphql-config/pull/1171 very soon!
