### ISSUE TITLE
Check for GRAPHQL_ENDPOINT first

### ISSUE THREAD

**Issue by bdougie** [kamilkisiela/graphql-config#12]
I am curious to know if there is a specific reason for the order in which this plugin checks for the GraphQL URL. I ask because I am working on an integration with graphcool and Netlify but Netlify needs to use the [GRAPHQL_ENDPOINT](https://github.com/graphcool/graphql-config/blob/master/src/index.ts#L47-L57) and it won't work if I have a local .graphqlrc/request URL.

Is it possible to check for the GRAPHQL_ENDPOINT first and then fallback to the checks for the package.json or the .graphqlrc

```js
export function parse (path: string = process.cwd()): Config {
  try {
    const packageJson = require(`${path}/package.json`)
    if (packageJson.hasOwnProperty('graphql')) {
      return parseConfigJson(packageJson.graphql)
    }
  } catch (ex) {
    // do nothing here
  }

  try {
    const graphqlrc = JSON.parse(readFileSync(`${path}/.graphqlrc`, 'utf-8'))
    return parseConfigJson(graphqlrc)
  } catch (ex) {
    // do nothing here
  }

  if (process.env.hasOwnProperty('GRAPHQL_ENDPOINT')) {
    ...
  }

  throw new Error('Couldn\'t find a GraphQL config. Please refer to https://github.com/graphcool/graphql-config')
}
```

Would there be any limitation to doing this? My thought would be the GRAPHQL_ENDPOINT would take precedent over the .graphqlrc request URL.

```js
export function parse (path: string = process.cwd()): Config {

  if (process.env.hasOwnProperty('GRAPHQL_ENDPOINT')) {
    ...
  }

  try {
   ...
  } catch (ex) {
    // do nothing here
  }

  try {
  ...
  } catch (ex) {
    // do nothing here
  }

  throw new Error('Couldn\'t find a GraphQL config. Please refer to https://github.com/graphcool/graphql-config')
}
```

**Comment by Rick83600** [comment]
+1 it would be great to change this order

**Comment by danielrearden** [comment]
As of version 3.0, the endpoint url can be specified using the `schema` option. `graphql-config` uses string interpolation to provide environmental variables, so it's possible to do something like:

```
schema: ${GRAPHQL_ENDPOINT}
```

You can also provide a fallback value if the environmental variable doesn't exist:

```
schema: ${GRAPHQL_ENDPOINT:"./graphql/schema.json"}
```

If this still doesn't meet your needs, please let us know by opening a new issue with an explanation of your use case.
