### ISSUE TITLE
Wrong peerDependencies?

### ISSUE THREAD

**Issue by muuvmuuv** [kamilkisiela/graphql-config#121]
I'm using GatsbyJS and it seems that it is installing this package which gives me this error:

```
npm WARN graphql-config@2.0.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
```

Is this correct? I'm using graphql 14.x and I get no errors with Gatsby on building my website.

**Comment by kamilkisiela** [comment]
Try out the latest version, it includes v14.
