### ISSUE TITLE
Environment variables not loaded from .env file.

### ISSUE THREAD

**Issue by BenoitRanque** [kamilkisiela/graphql-config#1319]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `yarn generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When using environment variables in a configuration file, the environment is not loaded from a '.env` file in the root directory.
If present, the defaults are used, if not, the operation fails.

**To Reproduce**

Create a config file that uses environment variables to specify endpoint or header values.
I was originally using `.graphqlrc.yaml` with templated strings as documented [here](https://the-guild.dev/graphql/config/docs/user/schema#environment-variables).
```yaml
schema:
  - ${GRAPHQL_ENDPOINT}:
documents:
  - src/**/*.{gql,graphql,ts,tsx}
# removed codegen config
```
Generating code using graphql codegen and type completion with the vscode graphql extension both fail.
The LSP produces the following error message:
```
      Unable to find any GraphQL type definitions for the following pointers:
        
          - undefined
```
The environment variable(s) are set in a `.env` file in the root directory.

**Expected behavior**
Environment variables should be loaded and the endpoint accessible.

**Environment:**

- OS: Windows 11
- GraphQL Config Version: 2
- NodeJS:  18.12.1

**Additional context**

I was able to workaround this issue by using a `.graphqlrc.js` file instead, and loading dotenv myself:
```js
require('dotenv').config();
module.exports = {
  schema: [
    {
      [process.env.OPS_API_GRAPHQL_ENDPOINT]: {
      },
    },
  ],
};

```

**Comment by ardatan** [comment]
`.env` files are specific to `dotenv` library. You should load them by yourself. This is not a bug.

**Comment by BenoitRanque** [comment]
That makes sense, must be something else down the chain that broke. Closing this issue.
