### ISSUE TITLE
Support schema registry such as `apollo-engine` similar to graphql-codegen

### ISSUE THREAD

**Issue by kdawgwilk** [kamilkisiela/graphql-config#1367]
**Describe the solution you'd like**

I would like to describe a schema config that lives in a schema registry such as Hive or Apollo engine

```ts
const supergraphConfigSchemaRegistry = {
  'apollo-engine': {
    engine: {
      apiKey: process.env.APOLLO_KEY!,
    },
    graph: '<GraphId>',
    variant: '<GraphVariant>',
  },
}
```

**Describe alternatives you've considered**

If I could pass an async function to the schema config prop I could do this fetching myself to load the schema from some remote service

**Additional context**

https://the-guild.dev/graphql/codegen/docs/config-reference/schema-field#apollo-engine

**Comment by kdawgwilk** [comment]
Could I do this with an extension and loader?

**Comment by kdawgwilk** [comment]
Yeah i ended up doing something like this
```ts
import { CodegenConfig } from '@graphql-codegen/cli';
 
const config: CodegenConfig = {
  schema: [
    {
      'http://localhost:3000/graphql': { // Url to registry such as Hive
        headers: {
          Authorization: 'YOUR-TOKEN-HERE',
        },
      },
    },
  ],
};
export default config;
 
```

**Comment by dotansimha** [comment]
Yeah, the example above is the right way to go. It's documented here: https://the-guild.dev/graphql/codegen/docs/config-reference/schema-field#headers
