### ISSUE TITLE
findSync doesn't work with js files because the loader is async

### ISSUE THREAD

**Issue by lukpsaxo** [kamilkisiela/graphql-config#1454]
I discovered this debugging a issue with the eslint plugin.

https://github.com/kamilkisiela/graphql-config/blob/master/src/helpers/cosmiconfig.ts#L94

needs to load the jsSync loader instead of the js one, otherwise when you use the findSync methods on this package, a promise is passed as the config to graphql-config.

**Comment by dimaMachina** [comment]
fixed in 5.1.0 https://github.com/kamilkisiela/graphql-config/releases/tag/v5.1.0

will be bumped in graphql-eslint too today
