### ISSUE TITLE
Config not found as of `5.1.2`

### ISSUE THREAD

**Issue by alecmev** [kamilkisiela/graphql-config#1506]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm run generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

Works fine in `5.1.0`. Most likely Cosmiconfig-related, as there is a traversal-related breaking change in v9: https://github.com/cosmiconfig/cosmiconfig/releases/tag/v9.0.0 Experiencing this problem in `@graphql-eslint/eslint-plugin@4.0.0-alpha.4` (it claims that there's no schema, despite it being defined in the config). The fastest fix is probably to add `searchStrategy: 'global'`, as per Cosmiconfig's release notes.

**Comment by janthomasQS** [comment]
If you are using pnpm you can use `"pnpm": {
    "overrides": {
      "graphql-config@^5.1.0" : "5.1.0"
    },` in your package json as a workarround until this is fixed

**Comment by jaydenseric** [comment]
@janthomasQS thanks for that workaround! For the regular npm CLI:

```json
{
  "overrides": {
    "graphql-config": "5.1.0"
  },
}
```

Our `.graphqlrc.json` looks like this, in case there is something about it that reproduces the accidental breaking change introduced in a patch release (`graphql-config@5.1.1` https://github.com/kamilkisiela/graphql-config/compare/v5.1.0...v5.1.1):

```json
{
  "$schema": "https://unpkg.com/graphql-config/config-schema.json",
  "schema": "schema.graphql",
  "documents": "(components|helpers|hooks|pages)/**/*.{mts,ts,tsx}"
}
```

**Comment by bmulholland** [comment]
@gvdp it was fixed, but then regressed: https://github.com/graphql-hive/graphql-config/issues/1726
