### ISSUE TITLE
Usage information incorrect: `loadConfig` doesn't exist

### ISSUE THREAD

**Issue by mrowles** [kamilkisiela/graphql-config#206]
Using v2.2.1, there is no exported member for `loadConfig` in `graphql-config`, unless I'm missing something here?

```
import {loadConfig} from 'graphql-config';

async function main() {
  const config = await loadConfig();

  const schema = await config.getDefault().getSchema();
}
```

I also assume this will return a GraphQlConfig type, which then has no exported members for `getDefault()`.

**Comment by kamilkisiela** [comment]
@mrowles The API you're using is v3 not v2, please run:

    $ yarn add graphql-config@next
