### ISSUE TITLE
Not updating from URL

### ISSUE THREAD

**Issue by nuclearspike** [kamilkisiela/graphql-config#21]
I love this package. However, recently it stopped updating and I'm not sure what to do to get it going again.

Is there any command I can do to force a refresh or a file I can delete to clear its cache to make it pull again?

I'm using the package.json option:
```
"graphql": {
    "request": {
      "url": "http://localhost:4000/queries"
    }
  },
```
The GraphQL endpoint is a Rails server. It had been working, and when I do a deploy script it will run and that script builds with the correct schema, but not during the normal process of running the dev server. The result is that my browser app throws console errors because I'm referencing things that it doesn't know exist. I don't know if it was a combination of updating a package or node, or something else.

Ideas?

**Comment by pbassut** [comment]
Having the same issue.

**Comment by danielrearden** [comment]
This sounds like an issue specific to whatever tool or library is consuming your configuration. If you are still experiencing this issue, please provide additional details around how your config is actually being used. In the meantime, I'm closing this issue since it's pretty old.
