### ISSUE TITLE
Support GET in addition to POST

### ISSUE THREAD

**Issue by brunolemos** [kamilkisiela/graphql-config#23]
I was trying to use it with [GraphQL Hub](https://www.graphqlhub.com/) endpoint, but it just accepts GET, not POST, so I get this error: `'Cannot POST /playground'`.

I see `POST` is hard coded [here](https://github.com/graphcool/graphql-config/blob/master/src/index.ts#L71), so why not a config to change this?

**Comment by schickling** [comment]
Good point @brunolemos. We'll take this feedback into account while for our upcoming refactor.

**Comment by MrRhodes** [comment]
Hello, was this feedback ever acted on? Is it still not possible?

**Comment by remidebette** [comment]
Hi, is it still not supported?

**Comment by ardatan** [comment]
It's supported like below;
```
schema: 
  - http://localhost:3000/graphql:
      method: GET
```

Could you try like above?

**Comment by remidebette** [comment]
Thank you for the response.
I am using the IntelliJ JS GraphQL plugin which in turn uses this library as explained [here](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide#working-with-graphql-endpoints-and-scratch-files)

In that case, their config file `.graphqlconfig` should be a json. 
Is the equivalent `"method": "GET"` ? 
(It does not look like it is working)

**Comment by danielrearden** [comment]
@remidebette Sorry for the late response. To answer your question, the equivalent JSON would look like this: 

```
{
   "schema": [
      {
         "http://localhost:3000/graphql": {
            "method": "GET"
         }
      }
   ]
}
```

However, it doesn't appear that particular plugin supports v3 yet. Unfortunately, there's nothing actionable here since we already support the necessary syntax. We'll do what we can to help any tools that use graphql-config migrate to the latest version.
