### ISSUE TITLE
Only works with npm run start

### ISSUE THREAD

**Issue by pbassut** [kamilkisiela/graphql-config#24]
It only picks up the config if I run `npm run start`, that is, run the packager manually. If I run `react-native run-ios` it won't pick it up

**Comment by schickling** [comment]
Good point! We're planning to refactor graphql-config quite a bit and will take this feedback into account!

**Comment by pbassut** [comment]
I can't archive the app. 
This might be related I guess?
I created an issue here: https://github.com/graphcool/babel-plugin-react-relay/issues/20

**Comment by pbassut** [comment]
@schickling Will this ever be addressed or there's a new tool I'm not aware of?

**Comment by schickling** [comment]
This is most likely an issue with a tool using `graphql-config`. Are you referring to `babel-plugin-react-relay`? If so, it's deprecated in favour of Relay Modern's compile system.
