### ISSUE TITLE
Create PRs for GraphQL plugins

### ISSUE THREAD

**Issue by schickling** [kamilkisiela/graphql-config#27]
In collaboration with Facebook, Apollo and apis.guru we've settled on the [new spec](https://github.com/graphcool/graphql-config/blob/config-protocol/specification.md) for `graphql-config`. The next step is to create PRs for the following GraphQL plugins and tools:

- [x] https://github.com/graphql/graphql-language-service cc @asiandrummer 
- [ ] https://github.com/kumarharsh/graphql-for-vscode cc @kumarharsh
- [x] https://github.com/jimkyndemeyer/js-graphql-intellij-plugin cc @jimkyndemeyer
- [ ] https://github.com/rmosolgo/language-graphql cc @rmosolgo
- [x] https://github.com/apollographql/eslint-plugin-graphql cc @jnwng
- [ ] https://github.com/jparise/vim-graphql cc @jparise
- [ ] https://github.com/orionsoft/atom-graphql-autocomplete cc @nicolaslopezj
- [ ] https://github.com/nodkz/babel-plugin-transform-relay-hot cc @nodkz
- [ ] https://github.com/relayjs/eslint-plugin-relay cc @kassens @pranaygp

Issues/PRs:

- [ ] https://github.com/relayjs/eslint-plugin-relay/issues/4
- [x] https://github.com/graphql/graphql-language-service/pull/130
- [x] https://github.com/apollographql/eslint-plugin-graphql/pull/80
- [ ] https://github.com/jparise/vim-graphql/issues/2

**Comment by asiandrummer** [comment]
Sorry I've been away for a bit - merged the PR this morning to resolve my end. lmk if you needed anything else from me!

**Comment by jparise** [comment]
The current specification link (now that it's been merged to `master`): https://github.com/graphcool/graphql-config/blob/master/specification.md

**Comment by jvbianchi** [comment]
For VSCode there's also this plugin https://github.com/stephen/vscode-graphql

**Comment by kassens** [comment]
`eslint-plugin-relay` intentionally doesn't consume a schema so that it is fast (even if the schema is massive)

**Comment by jimkyndemeyer** [comment]
js-graphql-intellij-plugin will be moving to the graphql-config format with the 2.0 release that is currently in alpha: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases

I have schemaPath, includes, excludes, projects, and endpoints working. Hope to include it in the next alpha within the next couple of weeks.

**Comment by danielrearden** [comment]
Closing this issue since it's stale and no longer relevant. We'll track adoption of v3 in a separate issue.
