### ISSUE TITLE
How do I work with two endpoints?

### ISSUE THREAD

**Issue by orome** [kamilkisiela/graphql-config#338]
Currently I'm using something like the following to work with two different endpoints that I switch between in my work (a local and a remote), with the consequence that I (need to manually) overwrite the schema file when I switch between them. 

Is there a way to do this with a different schema file for each endpoint? What is the correct idiom for working with (and switching between) two endpoints?

```
{
  "name": "My Schema",
  "schemaPath": "_schema.graphql",
  "extensions": {
    "endpoints": {
      "Local GraphQL Endpoint": {
        "url": "http://localhost:5000",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      },
      "Remote GraphQL Endpoint": {
        "url": "http://my.remote.io",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

**Comment by akomm** [comment]
In my IDE, the files are detected correctly, when put in different folders. Sadly not when prefixed or suffixed under the same directory. Also environment variables do not work under `schemaPath` config key.

**Comment by akomm** [comment]
In my IDE, the `.graphqlconfig` files are detected correctly, when put in different sub folders. Sadly not when the name is prefixed or suffixed under the same directory - maybe possible via manually adding extension type. Also environment variables do not work under `schemaPath` config key.

IDE used: phpstorm/webstorm (jetbrains)

**Comment by danielrearden** [comment]
You can now specify separate projects inside your config file as show [here](https://graphql-config.com/usage#projects) in the docs.
