### ISSUE TITLE
Release new version with all dependency bumps applied

### ISSUE THREAD

**Issue by codepunkt** [kamilkisiela/graphql-config#380]
There's a problem using your package with yarn v2. Could you please release a new version based on current master? This would most likely fix the problems caused by dependencies of `graphql-config`.

**Comment by kamilkisiela** [comment]
@codepunkt Which version of GraphQL Config are you using right now?

**Comment by rossdm** [comment]
@kamilkisiela Shouldn't the `latest` version of this library in npm point to the v2 version? Currently users are being prompted to upgrade to the alpha.

example:

```
npm view graphql-config dist-tags
 
{
  latest: '3.0.0-alpha.17',
  guild: '3.0.0-alpha.13',
  next: '3.0.0-alpha.18'
}
```
Expected behavior described [here](https://github.com/twbs/bootstrap/issues/18520#issuecomment-163890539).

**Comment by danielrearden** [comment]
v3 is now out of alpha and the latest tag in npm correctly points to `3.0.3`. If there are still issues with installing the latest version using yarn, please let us know.
