### ISSUE TITLE
Custom CosmicConfig Key

### ISSUE THREAD

**Issue by acao** [kamilkisiela/graphql-config#395]
For this line:

https://github.com/kamilkisiela/graphql-config/blob/35419e0fb52cd08d1534b763076fd81ef67a5c8a/src/helpers.ts#L138

if we make `graphql` value customizeable, our users can provide their own keyword for file names! :sunglasses:

**Comment by acao** [comment]
@ardatan would it be helpful if i created a PR for this today?

**Comment by kamilkisiela** [comment]
#427
