### ISSUE TITLE
Request: Version 3 changelog/description

### ISSUE THREAD

**Issue by wheeler** [kamilkisiela/graphql-config#419]
I am in a situation where different graphql packages I'm using import a version 2 and a version 3 alpha of graphql-config. The inner dependencies on `@graphql-toolkit` are strictly versioned in this package and this seems to be causing me some yarn difficulty when it is trying to resolve the versions.

It might be simplest for me to use resolutions to specify only one version of `graphql-config` but I have no idea what the difference is in version 3. There's no mention in the readme, there's no `CHANGELOG.md`, and the alpha releases are not listed on the releases tab. A major version in semver indicates breaking changes - it would be helpful to at least know what those are.

**Comment by kamilkisiela** [comment]
[`CHANGELOG.md`](https://github.com/kamilkisiela/graphql-config/blob/master/CHANGELOG.md) and  [Migration chapter](https://graphql-config.com/migration) in docs
