### ISSUE TITLE
Deciding which project a file belongs to

### ISSUE THREAD

**Issue by martijnwalraven** [kamilkisiela/graphql-config#43]
An IDE or language server needs a way to decide what schema to use to interpret a particular file. Although projects in the `.graphqlconfig` can specify `includes`/`excludes`, there is nothing keeping these from overlapping.

The current implementation of [`getConfigForFile`](https://github.com/graphcool/graphql-config/blob/c236f0943c120cabf816df461d32d0740834b86c/src/GraphQLConfig.ts#L31-L42) always returns the first project that includes a file. If that is the intended behavior, we should probably make that part of the spec.

One situation that seems counterintuitive if we do so is if project A doesn't specify any `includes`/`excludes`, but project B explicitly includes a file. If project A is listed first in the config, it will match every file, and project B will be ignored.

**Comment by schickling** [comment]
@asiandrummer I remember you had some fairly specific behaviour in mind back when you implemented this. Can you share your thoughts again?
