### ISSUE TITLE
Generate local schema.json from endpoint, then validate documents from local schema.json

### ISSUE THREAD

**Issue by sarink** [kamilkisiela/graphql-config#451]
I feel like what I want is pretty reasonable, but I can't find a way to configure it.

I would like to generate a local schema.json file from a running endpoint. Once that has been downloaded, I would like to validate my queries/documents against this local schema.json file.

I would also like to be able to do this for multiple `projects`.

However, it seems that the `schema` key was built to only accept one or the other (endpoint url or local json), and once you've configured it, your `documents` key will utilize the same value to validate against.

Can someone point me in the right direction? Thanks

**Comment by danielrearden** [comment]
You can now configure separate projects inside your config as shown [here](https://graphql-config.com/usage#projects) in the docs.
