### ISSUE TITLE
Reference info from separate files

### ISSUE THREAD

**Issue by blackxored** [kamilkisiela/graphql-config#49]
Like the serverless framework I think we should be able to reference specific vars from external files (e.g json, yaml, JS files) to configure our endpoints. In my particular flow, there's a complicated auth process to which I tap in and write the token to an external file after finished. Given we've no access to the shell that tools like Playground ran from, we can't update the env var. For now, we're modifying this file directly but it's a hassle to avoid committing to VCS.

**Comment by schickling** [comment]
Hi @blackxored thanks for bringing this up. This is actually something we're currently trying to improve. While this is not yet directly supported by `graphql-config`, the `graphql-cli` already passes injects your environment variables into the GraphQL Playground when invoked via `graphql playground`. Here is an example:

```sh
# opens playground and populates `YOUR_ENV_VAR` for .graphqlconfig
YOUR_ENV_VAR="your-value" graphql playground
```

I'd love to hear further thoughts on how variables could be directly injected into `graphql-config`. Maybe via a `dotenv` extension?

**Comment by blackxored** [comment]
Yes but the problem is once the token refreshes (OAuth flows), I need to pretty much restart the app.

**Comment by schickling** [comment]
That's true. Could you describe your ideal design?

**Comment by blackxored** [comment]
Not sure how feasible it would be, but basically allow specifying a file e.g `${file:config.json:auth.token}` that gets re-evaluated on change (or alternatively, read/diffed on every request)

**Comment by schickling** [comment]
I think while the reading/parsing part could be supported by `graphql-config`, I think it would be the tool's job to listen for changes of other files since the tool is running the process and not `graphql-config`.

Can you further describe this in more detail?

**Comment by blackxored** [comment]
Yes, watching is definitely something that needs to be handled by tools (in my example, Playground).

**Comment by kbrandwijk** [comment]
I think a good first step could be support for `${file:}` and `${env:}` like serverless has.

**Comment by kbrandwijk** [comment]
See https://serverless.com/framework/docs/providers/aws/guide/variables#current-variable-sources. Also discussed in #46 and #47. I will create a new issue with a proposal soon.
