### ISSUE TITLE
Question: how to deal with Gatsby's "arbitrary fieldName"

### ISSUE THREAD

**Issue by romainbessugesmeusy** [kamilkisiela/graphql-config#499]
Wit Gatsby [GraphQL source plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql), we are asked to define a root level "fieldName" that surrounds the actual query.
Using IntelliJ graphQL plugin, which relies on graphql-config, there's no autocompletion because it doesn't receive the arbitrary fieldName from the endpoint. Do you have any clue ?

<img width="364" alt="Capture d’écran 2020-04-07 à 16 18 59" src="https://user-images.githubusercontent.com/3127404/78681341-e6eb0b80-78ec-11ea-9b0a-37e36a248195.png">

The Gatsby-Source-GraphQL config
```javascript
    {
      resolve: 'gatsby-source-graphql',
      options: {
        // Arbitrary name for the remote schema Query type
        typeName: 'apiMG',
        // Field under which the remote schema will be accessible. You'll use this in your Gatsby query
        fieldName: 'apiMG',
        // Url to query from
        url: `${process.env.GATSBY_API_URL + process.env.GATSBY_API_KEY}`,
        refetchInterval: 60,
      },
    },
```

The .graphqlconfig file

```json
{
  "name": "Pimcore",
  "schemaPath": "./pimcore.graphql",
  "extensions": {
    "endpoints": {
      "Remote Pimcore Endpoint": {
        "url": "URL",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

**Comment by kamilkisiela** [comment]
@romainbessugesmeusy IntelliJ GraphQL Plugin doesn't use JavaScript implementation of `graphql-config`, they only share json / yaml syntax. You should submit an issue in plugin's repository.
