### ISSUE TITLE
Provide a jsonschema for editors to consume .graphqlconfig

### ISSUE THREAD

**Issue by stephen** [kamilkisiela/graphql-config#52]
It would be nice to provide a jsonschema file for the format of .graphqlconfig. This could enable editors, i.e. [`vscode`](https://code.visualstudio.com/docs/languages/json#_json-schemas-settings) to provide autocomplete and hints for how to configure `.graphqlconfig` properly.

**Comment by schickling** [comment]
Great idea @stephen. This is a great opportunity for a PR contribution. Do you want to take a stab at this?

**Comment by captDaylight** [comment]
Is this closed as of #53 ?

**Comment by kwbskf** [comment]
FYI: I came here specifically looking for such a thing, or to ask that someone do it.  Should have known the request would already be registered here. LOL.

I am certainly not the best choice for doing it myself.  Someone intimately familiar with the graphqlconfig file's expected contents would be a better choice.  

But I can echo the sentiment:  it sure would be nice for VSCode (et. al.)  to be able to automatically syntax-check and offer tooltip hints for what each element is supposed to be.  Lots of other JSON config files already have this, and you can find them at schemastore.org (and you just configure VSCode with a "json.schemas" item that is an array of objects that each have a "fileMatch" and a "url" pointing to that schema on schemastore.org, once it's there).

**Comment by jimkyndemeyer** [comment]
I've created a JSON schema as part of the 2.0 of js-graphql-intellij-plugin that you're welcome to use: 

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/resources/com/intellij/lang/jsgraphql/ide/project/graphqlconfig/javascript/graphql-config-schema.json

**Comment by danielrearden** [comment]
This is now available in the repo. [Direct link](https://raw.githubusercontent.com/kamilkisiela/graphql-config/master/config-schema.json)
