### ISSUE TITLE
Broken release of the GraphQL Config

### ISSUE THREAD

**Issue by wtrocki** [kamilkisiela/graphql-config#542]
GraphQL config 3.0.1 stopped working from the source code:
graphql-config/config.d.ts(1,37): error TS2307: Cannot find module './types'.

https://circleci.com/gh/aerogear/graphback/4025?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by wtrocki** [comment]
@kamilkisiela pinging directly in case you have missed that. 
I have got the info from other community members using package that release is broken.

**Comment by kamilkisiela** [comment]
@wtrocki [`3.0.2`](https://github.com/kamilkisiela/graphql-config/releases/tag/v3.0.2)
