### ISSUE TITLE
New typings are not giving ability to build config programatically

### ISSUE THREAD

**Issue by wtrocki** [kamilkisiela/graphql-config#543]
New release breaks the ability to create config from the code. 
There is no more interface that can be used to reflect valid config

<img width="453" alt="Screenshot 2020-05-05 at 12 40 19" src="https://user-images.githubusercontent.com/981838/81062364-b9828500-8ecd-11ea-97bd-ae5ad90916d3.png">

**Comment by wtrocki** [comment]
Note: This is not a biggie as I can build config as untyped object but mentioning it if that was not intentional some side effect

**Comment by danielrearden** [comment]
@wtrocki You can import `IGraphQLConfig` for that purpose, unless am I misunderstanding what you're referring to.

**Comment by wtrocki** [comment]
Yep.. It was restored from the imports. Closing
