### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by samuelcastro** [kamilkisiela/graphql-config#555]
The usage of this library is really confused or/and not clear, for instance, I can't find a way to generate schemas from a given url using a simple command, the ways I could find was through using IDE's extensions, but I can't get any extension work, specially with the new version. (I'm a vscode user)

**Comment by kamilkisiela** [comment]
It's designed for library authors and internal tools and the main purpose of `graphql-config` is to help them with handling schema/documents loading and consuming configuration. Plus, it's one config for all tools, so you shouldn't need to write multiple config files.

Previous version had CLI to introspect GraphQL API and to write the result to a file but that's in my opinion should be done outside of GraphQL Config, for example in [GraphQL CLI](https://github.com/Urigo/GraphQL-CLI).

To introspect schemas use [GraphQL Inspector](https://graphql-inspector.com/docs/essentials/introspect) (GraphQL CLI will have it soon).

**Comment by arjun-kava** [comment]
Following code worked for me.

graphql.config.yml
```yml
schema: http://localhost:8081/graphql
extensions:
  codegen:
    generates:
      ./schema.graphql:
        - schema-ast
```

package.json
```json
"scripts": {
  "codegen": "graphql codegen --config graphql.config.yml"
}
```

**Comment by arjun-kava** [comment]
@samuelcastro, Yes. I am using GraphQL CLI
