### ISSUE TITLE
version 2.0 documentation

### ISSUE THREAD

**Issue by twmillett** [kamilkisiela/graphql-config#557]
Some tools still use version 2.0, but it's impossible to find documentation on that.  The link on the main page 404s, for example.

Can you please surface the 2.0 documentation somewhere?  Thanks!

**Comment by ardatan** [comment]
@twmillett 
![image](https://user-images.githubusercontent.com/20847995/83312915-ce2c1180-a21c-11ea-9a00-87ed95d768e4.png)

So you can find old documentation below;
https://github.com/kamilkisiela/graphql-config/tree/legacy#graphql-config-api
