### ISSUE TITLE
[doc] Please update documentation

### ISSUE THREAD

**Issue by nemanjamilosavljevic-newtron** [kamilkisiela/graphql-config#669]
The link for the `usage docs` should be updated. Currently, it leads to a **Page Not Found** screen.
https://graphql-config.com/introduction/

![image](https://user-images.githubusercontent.com/77624664/113688451-9954da80-96c9-11eb-8dc1-50791658dc2d.png)

**Comment by kamilkisiela** [comment]
thanks

**Comment by nemanjamilosavljevic-newtron** [comment]
@kamilkisiela you're welcome!
Has the link/page been updated? I still see the same Page not found message.
