### ISSUE TITLE
Config is not loaded from package.json

### ISSUE THREAD

**Issue by ionut-botizan** [kamilkisiela/graphql-config#692]
**Describe the bug**
The default search locations of `cosmicconfig` are overwritten and the `package.json` option is left out, so configs are not loaded from it.
The culprit: https://github.com/kamilkisiela/graphql-config/blob/master/src/helpers/cosmiconfig.ts#L71
The original: https://github.com/davidtheclark/cosmiconfig/blob/main/src/index.ts#L109

**To Reproduce**
1. Define a `graphql` configuration in `package.json`
2. Try to load it using `loadConfigSync`

A Codesandbox example where configurations are loaded from `.#rc` files, `#.config.js` files, but not from `package.json`:
https://codesandbox.io/s/graphql-config-ignoring-packagejson-nergw?file=/src/index.js

**Expected behavior**
The `loadConfigSync` function should load the `graphql` configuration from the `package.json` file, as per the [`graphql-config` documentation](https://graphql-config.com/usage) and the default behavior of `cosmiconfig`

**Environment:**

- OS: All
- GraphQL Config Version: 3.2.0
- NodeJS: All

**Comment by kamilkisiela** [comment]
`v3.3.0`
