### ISSUE TITLE
Make schemaPath optional

### ISSUE THREAD

**Issue by kbrandwijk** [kamilkisiela/graphql-config#75]
Contrary to the specification, schemaPath is currently required here:
https://github.com/graphcool/graphql-config/blob/08a0da8f408f96d45eccee61013c87a242ce3e9a/src/types.ts#L16

This makes this a very awkward type definition, that project-based config files cannot follow:
https://github.com/graphcool/graphql-config/blob/08a0da8f408f96d45eccee61013c87a242ce3e9a/src/types.ts#L24-L26

Because there is no top-level schemaPath for project-based configs

**Comment by schickling** [comment]
I think you're right. This should probably be refactored to not require `schemaPath` on the root level if `projects` is present. @asiandrummer @IvanGoncharov  what are your thoughts on this?

**Comment by kamilkisiela** [comment]
Hi there, it's [The Guild](http://the-guild.dev/) :) We're working on a new version of GraphQL Config. The goal is to make it platform agnostic, flexible enough to use with any tool and framework, reduce the bundle size and a lot more and what's even more important, bring it back to life and keep maintaining.

New changes #162 are already merged into master and `v3.0.0-alpha.13` is released.

We made `schema` optional if `projects` is present.

@kbrandwijk I see you're very active here, we'd love to hear your suggestions on the new API!
