### ISSUE TITLE
Support .cjs extension for .graphqlrc

### ISSUE THREAD

**Issue by nurdism** [kamilkisiela/graphql-config#756]
**Describe the bug**
graphql-config does not detect .cjs extension for a .graphqlrc file

**To Reproduce**
create a `.graphqlrc.cjs`
run graphql cli
```
[ConfigNotFoundError: GraphQL Config file is not available in the provided config directory: [dir] Please check the config directory.]
```

**Expected behavior**
`.graphqlrc.cjs` to be found and read

**Environment:**

- OS:
Debian Lunix
- GraphQL Config Version:
  graphql@15.5.1
  graphql-cli@4.1.0
  graphql-config@4.0.1
- NodeJS:
  v14.17.6

**Comment by IanVS** [comment]
This is necessary for projects which have set `"type": "module"` in their package.json (as I have).  Otherwise, there's seemingly no way that I can create a javascript configuration file.

**Comment by tvvignesh** [comment]
@kamilkisiela You can assign this issue to me. I will have a look.

**Comment by tvvignesh** [comment]
@ardatan PR for this here: https://github.com/kamilkisiela/graphql-config/pull/859
