### ISSUE TITLE
Extension doesn't include CodeFileLoader

### ISSUE THREAD

**Issue by azz** [kamilkisiela/graphql-config#817]
The [`CodeFileLoader`](https://www.graphql-tools.com/docs/api/classes/loaders_code_file_src.CodeFileLoader) loader isn't currently added to the `documents` loader registry, meaning if you want to include fragments from your source code (usually found using `graphql-tag-pluck`), they won't be detected.

https://github.com/kamilkisiela/graphql-config/blob/89767c8b3dc56a930f42e5e96bcbc43bd5644f41/src/extension.ts#L43

Is this deliberate?

**Comment by ardatan** [comment]
Yes because CodeFileLoader has some big dependencies
