### ISSUE TITLE
npm minimatch dependency

### ISSUE THREAD

**Issue by PatrickYoussef** [kamilkisiela/graphql-config#970]
**Is your feature request related to a problem? Please describe.**

In graphql-config latest release 4.1.0, its dependency minimatch is still strictly at 3.0.4. It should be greater than 3.0.5 at least to remove a vulnerability issue

**Describe the solution you'd like**
There should be a new release with the minimatch version at least 3.0.5

**Comment by B2o5T** [comment]
fixed in `graphql-config@4.2.0` 🚀
